type Query {
  computers(standalone: Boolean): [Computer!]!
  computer(where: WhereUniqueComputerInput!): Computer
  computerGroups: [ComputerGroup!]!
  computerGroup(where: WhereUniqueComputerGroupInput!): ComputerGroup
}
