name: Compile LaTeX on Push

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          docker_image: docker.io/critteros/texlive-full-jsx
          args: -pdf -file-line-error -halt-on-error --shell-escape -interaction=nonstopmode -jobname=Engineering-Thesis

      - name: Upload thesis PDF
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Engineering-Thesis
          path: Engineering-Thesis.pdf
